seed: 1

# ===========> Training configs <===========
batch_size: 256
epochs: 30  
num_workers: 16
label_smoothing: 0.
pin_memory: True

# Optimizer
# SGD lr: 0.05 decay_rate 0.01
opt: SGD   # 'adamw' # 'adam'
opt_eps: null
opt_betas: null
clip_grad: null
momentum: 0.9
weight_decay: 5.e-4     #0.05

# ==> Scheduler
lr: 0.01
lr_noise: null
warmup_lr: 1.e-5  #1.e-5
min_lr: 1.e-4 #1.e-4

sched: 'multistep'  
decay_milestones: [30]  # static lr
decay_rate: 0.2

warmup_epochs: 0
cooldown_epochs: 0
patience_epochs: 0
