seed: 1

# ===========> Perturbation configs <===========
edit_ratio: 0.9
expl_name: 'ig'
rank_type: '_rank'
flag_keep: 1

# ===========> Training configs <===========
batch_size: 256
epochs: 10  # Only 10 epochs for restricted fine-tuning
num_workers: 16
label_smoothing: 0.
pin_memory: True

# Optimizer
opt: SGD   
opt_eps: null
opt_betas: null
clip_grad: null
momentum: 0.9
weight_decay: 5.e-4     

# ==> Scheduler
lr: 0.1
lr_noise: null
warmup_lr: 1.e-5  
min_lr: 1.e-4 

sched: 'cosine'
# sched: 'multistep'
decay_milestones: [30, 50, 70]  # correspond to 'multistep'
decay_rate: 0.2   # correspond to 'multistep'

warmup_epochs: 1
cooldown_epochs: 0
patience_epochs: 0

